name: tests

on:
  push:
    branches: [ "main", "developer" ]
  pull_request:
    branches: [ "main", "developer" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_DATABASE: ticto_db
          MYSQL_ROOT_PASSWORD: developer
          MYSQL_DEFAULT_STORAGE_ENGINE: InnoDB
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, pdo_mysql, zip, bcmath, sockets

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache
        key: composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Ajustar permissões
      run: chmod -R 775 storage bootstrap/cache

    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: ticto_db
        DB_USERNAME: root
        DB_PASSWORD: developer
      run: php artisan migrate --force

    - name: Execute tests (Unit and Feature tests)
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: ticto_db
        DB_USERNAME: root
        DB_PASSWORD: developer
      run: php artisan test